insert into models (id_country, id_category, name, count, price) values ( 1, 8, 'Gears of War 2',0,1072.86);
insert into models (id_country, id_category, name, count, price) values ( 3, 3, 'Borderlands 2',10,562.08);
insert into models (id_country, id_category, name, count, price) values ( 3, 1, 'Tomboy',8,765.98);
insert into models (id_country, id_category, name, count, price) values ( 4, 1, 'Meteos',8,1627.72);
insert into models (id_country, id_category, name, count, price) values ( 1, 2, 'Resident Evil Code: Veronica',6,1599.64);
insert into models (id_country, id_category, name, count, price) values ( 4, 2, 'World of Goo',5,285.03);
insert into models (id_country, id_category, name, count, price) values ( 3, 8, 'System Shock 2',10,739.59);
insert into models (id_country, id_category, name, count, price) values ( 2, 9, 'Pokemon Silver Version',5,544.25);
insert into models (id_country, id_category, name, count, price) values ( 5, 6, 'Crysis',2,296.01);
insert into models (id_country, id_category, name, count, price) values ( 5, 3, 'Rayman 2: The Great Escape',10,1810.81);
insert into models (id_country, id_category, name, count, price) values ( 2, 5, 'Shin Megami Tensei: Persona 3 FES',1,1475.22);
insert into models (id_country, id_category, name, count, price) values ( 3, 9, 'The Elder Scrolls IV: Oblivion',7,435.52);
insert into models (id_country, id_category, name, count, price) values ( 4, 4, 'NCAA Football 2004',1,934.40);
insert into models (id_country, id_category, name, count, price) values ( 2, 5, 'The Elder Scrolls V: Skyrim',1,1165.06);
insert into models (id_country, id_category, name, count, price) values ( 5, 4, 'Tony Hawks Pro Skater 4',9,278.63);
insert into models (id_country, id_category, name, count, price) values ( 5, 2, 'Infamous 2',3,614.72);
insert into models (id_country, id_category, name, count, price) values ( 4, 6, 'Halo 3: ODST',8,1739.00);
insert into models (id_country, id_category, name, count, price) values ( 5, 5, 'Pharaoh Man',1,861.85);
insert into models (id_country, id_category, name, count, price) values ( 2, 5, 'Grand Theft Auto V',2,1709.32);
insert into models (id_country, id_category, name, count, price) values ( 5, 9, 'Rock Band 2',0,285.94);
insert into models (id_country, id_category, name, count, price) values ( 4, 2, 'World of Warcraft: The Burning Crusade',1,551.98);
insert into models (id_country, id_category, name, count, price) values ( 3, 4, 'Battlefield: Bad Company 2',6,1243.92);
insert into models (id_country, id_category, name, count, price) values ( 1, 8, 'Mirrors Edge',9,1328.02);
insert into models (id_country, id_category, name, count, price) values ( 4, 4, 'Gears of War 3',2,387.07);
insert into models (id_country, id_category, name, count, price) values ( 4, 2, 'Teenage Mutant Ninja Turtles: Turtles in Time Re-Shelled',1,610.67);
insert into models (id_country, id_category, name, count, price) values ( 4, 5, 'WCW Backstage Assault',1,365.29);
insert into models (id_country, id_category, name, count, price) values ( 4, 5, 'New Super Mario Bros.',6,1145.43);
insert into models (id_country, id_category, name, count, price) values ( 3, 1, 'The ICO & Shadow of the Colossus Collection',9,1454.46);
insert into models (id_country, id_category, name, count, price) values ( 2, 8, 'ECW Hardcore Revolution',8,1431.77);
insert into models (id_country, id_category, name, count, price) values ( 2, 4, 'Journey',9,1047.57);
insert into models (id_country, id_category, name, count, price) values ( 5, 6, 'Unreal Tournament 2004',9,1122.95);
insert into models (id_country, id_category, name, count, price) values ( 4, 7, 'WCW Nitro',5,1036.78);
insert into models (id_country, id_category, name, count, price) values ( 5, 4, 'Metroid Fusion',7,1340.04);
insert into models (id_country, id_category, name, count, price) values ( 1, 1, 'Geometry Wars: Retro Evolved 2',5,1301.78);
insert into models (id_country, id_category, name, count, price) values ( 5, 8, 'World of Warcraft: Cataclysm',3,1336.66);
insert into models (id_country, id_category, name, count, price) values ( 5, 7, 'Grand Theft Auto III',6,983.78);
insert into models (id_country, id_category, name, count, price) values ( 1, 1, 'Minecraft',7,1679.73);
insert into models (id_country, id_category, name, count, price) values ( 2, 9, 'Trials Evolution',4,1274.86);
insert into models (id_country, id_category, name, count, price) values ( 1, 1, 'WWF In Your House',6,1938.89);
insert into models (id_country, id_category, name, count, price) values ( 5, 2, 'Ninja Gaiden Black',7,1869.00);
insert into models (id_country, id_category, name, count, price) values ( 5, 2, 'Super Mario Bros.',4,340.50);
insert into models (id_country, id_category, name, count, price) values ( 1, 4, 'WWF War Zone',4,924.45);
insert into models (id_country, id_category, name, count, price) values ( 5, 8, 'MLB 10: The Show',8,609.57);
insert into models (id_country, id_category, name, count, price) values ( 5, 1, 'The Legend of Zelda: Twilight Princess',10,1840.84);
insert into models (id_country, id_category, name, count, price) values ( 2, 3, 'Mass Effect 2',9,931.55);
insert into models (id_country, id_category, name, count, price) values ( 4, 9, 'Tom Clancys Splinter Cell',3,998.58);
insert into models (id_country, id_category, name, count, price) values ( 5, 6, 'Planescape: Torment',7,1221.64);
insert into models (id_country, id_category, name, count, price) values ( 4, 2, 'Gears of War',3,751.43);
insert into models (id_country, id_category, name, count, price) values ( 2, 1, 'Demons Souls',1,1547.45);
insert into models (id_country, id_category, name, count, price) values ( 2, 5, 'MegaMan.EXE',1,1127.97);
insert into models (id_country, id_category, name, count, price) values ( 4, 3, 'Total War: Shogun 2',5,1740.01);
insert into models (id_country, id_category, name, count, price) values ( 3, 2, 'Tomb Raider',1,422.36);
insert into models (id_country, id_category, name, count, price) values ( 1, 3, 'FIFA 11',5,1628.08);
insert into models (id_country, id_category, name, count, price) values ( 5, 2, 'Donkey Kong Country Returns',10,790.97);
insert into models (id_country, id_category, name, count, price) values ( 5, 9, 'Castlevania: Dawn of Sorrow',4,599.71);
insert into models (id_country, id_category, name, count, price) values ( 4, 2, 'Tony Hawks Pro Skater',10,1141.22);
insert into models (id_country, id_category, name, count, price) values ( 5, 4, 'Super Paper Mario',1,1498.36);
insert into models (id_country, id_category, name, count, price) values ( 1, 7, 'Superbrothers: Sword & Sworcery EP',9,1456.25);
insert into models (id_country, id_category, name, count, price) values ( 5, 1, 'Eternal Darkness: Sanitys Requiem',4,340.47);
insert into models (id_country, id_category, name, count, price) values ( 1, 5, 'World Soccer Winning Eleven 6 International',1,926.63);
insert into models (id_country, id_category, name, count, price) values ( 1, 5, 'New Xbox Experience',5,536.67);
insert into models (id_country, id_category, name, count, price) values ( 1, 2, 'Final Fantasy XII',8,392.32);
insert into models (id_country, id_category, name, count, price) values ( 4, 8, 'Virtua Fighter 4: Evolution',4,1189.22);
insert into models (id_country, id_category, name, count, price) values ( 4, 6, 'Valkyria Chronicles II',5,1151.07);
insert into models (id_country, id_category, name, count, price) values ( 1, 3, 'Super Mario 64',6,1824.80);
insert into models (id_country, id_category, name, count, price) values ( 1, 6, 'Super Mario World',7,392.16);
insert into models (id_country, id_category, name, count, price) values ( 4, 4, 'NBA 2K11',10,1319.76);
insert into models (id_country, id_category, name, count, price) values ( 4, 1, 'Professor Layton and the Unwound Future',5,1825.42);
insert into models (id_country, id_category, name, count, price) values ( 3, 7, 'God of War: Chains of Olympus',10,738.16);
insert into models (id_country, id_category, name, count, price) values ( 2, 1, 'Shadow Complex',1,421.74);
insert into models (id_country, id_category, name, count, price) values ( 4, 3, 'Far Cry 2',3,1740.92);
insert into models (id_country, id_category, name, count, price) values ( 1, 9, 'WCW/nWo Thunder',8,305.64);
insert into models (id_country, id_category, name, count, price) values ( 5, 4, 'Call of Duty',5,1603.91);
insert into models (id_country, id_category, name, count, price) values ( 5, 6, 'Metroid Prime 3: Corruption',9,1692.52);
insert into models (id_country, id_category, name, count, price) values ( 5, 5, 'Super Stardust HD',8,381.55);
insert into models (id_country, id_category, name, count, price) values ( 5, 9, 'Lumines',3,1498.91);
insert into models (id_country, id_category, name, count, price) values ( 4, 9, 'Metroid Prime 2: Echoes',10,213.49);
insert into models (id_country, id_category, name, count, price) values ( 5, 5, 'Super Mario Bros. 3',10,948.49);
insert into models (id_country, id_category, name, count, price) values ( 1, 6, 'Ninja Gaiden',2,1449.68);
insert into models (id_country, id_category, name, count, price) values ( 5, 6, 'Metal Gear Solid: Peace Walker',8,1882.00);
insert into models (id_country, id_category, name, count, price) values ( 5, 9, 'The Orange Box',7,1204.17);
insert into models (id_country, id_category, name, count, price) values ( 2, 4, 'Mega Man',4,721.84);
insert into models (id_country, id_category, name, count, price) values ( 4, 9, 'Rome: Total War',2,1750.16);
insert into models (id_country, id_category, name, count, price) values ( 2, 3, 'Super Smash Bros. Melee',5,919.30);
insert into models (id_country, id_category, name, count, price) values ( 5, 4, 'Grand Theft Auto: Episodes from Liberty City',0,318.56);
insert into models (id_country, id_category, name, count, price) values ( 4, 5, 'Tekken 3',4,889.17);
insert into models (id_country, id_category, name, count, price) values ( 3, 3, 'Viva Piñata: Trouble in Paradise',0,1770.37);
insert into models (id_country, id_category, name, count, price) values ( 4, 8, 'Dead or Alive 2',9,540.41);
insert into models (id_country, id_category, name, count, price) values ( 3, 8, 'The World Ends With You',4,1457.02);
insert into models (id_country, id_category, name, count, price) values ( 2, 9, 'Elder Scrolls IV: Oblivion',8,880.16);
insert into models (id_country, id_category, name, count, price) values ( 1, 9, 'Tomba!',6,1746.54);
insert into models (id_country, id_category, name, count, price) values ( 1, 6, 'Resident Evil 2',4,242.18);
insert into models (id_country, id_category, name, count, price) values ( 3, 5, 'Half-Life',0,700.10);
insert into models (id_country, id_category, name, count, price) values ( 2, 4, 'SSX',3,1889.62);
insert into models (id_country, id_category, name, count, price) values ( 1, 2, 'Spyro: Year of the Dragon',10,1140.26);
insert into models (id_country, id_category, name, count, price) values ( 1, 9, 'NCAA Football 2003',10,874.65);
insert into models (id_country, id_category, name, count, price) values ( 2, 3, 'Super Mario Sunshine',9,241.15);
insert into models (id_country, id_category, name, count, price) values ( 5, 5, 'Super Mario 3D World',6,1051.20);
insert into models (id_country, id_category, name, count, price) values ( 2, 3, 'The Legend of Zelda: Ocarina of Time',1,444.65);
insert into models (id_country, id_category, name, count, price) values ( 3, 1, 'BioShock',7,767.76);

